### ISSUE TITLE
채널 데이터 및 채팅 데이터 관리를 위한 스키마 및 Entity 작성 

### ISSUE THREAD

**Issue by mrlee7** [booooomb/backend#5]
### 배경
- 플랫폼 내에서 유저간 소통할 수 있도록, 해당 플랫폼은 채팅 기능을 제공합니다. 
- 각 User(Client) 간 채팅을 위해 채팅방 및 수/발신하는 메시지 데이터를 저장할 수 있도록 합니다. 

### 작업 내용
- jpa entity 를 설계합니다. 

### 기대 효과
- 채팅 관련 로직시 해당 도메인, 엔티티를 용이하게 사용할 수 있기를 기대합니다.

**Comment by mrlee7** [comment]
@coderclcl  님 안녕하세요 :)  

jpa entity 작성을 위해 erd 초안 공유드립니다.  
러프하게 그려보았으며, 해당 엔티티를 기반으로 개선해나가고자 하는데 누락된 부분 혹은 수정 필요한 부분에 대해 코멘트 주시면 반영하도록 하겠습니다.  

감사합니다 (_ _)  

> https://drawsql.app/teams/junepil-lee/diagrams/chat
![image](https://github.com/booooomb/api/assets/54073761/8ff7494a-30a2-450d-964d-8631ebe38284)

**Comment by coderclcl** [comment]
오 drawSQL 깔끔하네요! 빠르게 틀 잡아주셔서 감사합니다 🙇 


몇 가지 떠오른 아이디어 공유 드려봅니다 ㅎ 

1. `keyword`와 `archived_keyword` 테이블을 하나로 합치면 어떨까 하는 생각이 들었습니다! 키워드가 top 10 rank에서 밀려나거나 재진입할 때마다 동일한 레코드가 두 테이블에서 업데이트되는 일이 빈번해질 것 같아 `keyword` 테이블에 `archived` 컬럼을 두는 것은 어떨지 제안드려봅니다 ㅎㅎ (컬럼 중복을 최소화할 수 있다는 장점이 있을 것 같습니다!) 

2. 생각해보니 `keyword`와 `chat_room` 도 거의 1:1의 동일한 개념이니 하나로 합쳐도 괜찮지 않을까 하는 생각이 드는군용,, 🤔 (둘을 분리해야할 이유가 크게 없다면 테이블 join 횟수를 줄이는 방향이 성능상 이점이 있지 않을까 생각했습니다)

3. (유찬님께서 회원가입 구현 방향을 제안해주셨던 기억이 있어서..) 모든 유저들의 정보를 저장하는 user 테이블을 제안드려봅니다 ㅎ 컬럼은 `id`(PK), `email`, `created_at` 정도로 생각했습니다. 

4. 챗과 유저의 관계가 N:M이고, 노티를 보낼 때 해당 챗에 참여한 멤버 리스트가 필요할 것 같아서, 챗에 참가한 멤버리스트를 저장하는 `chat_member` 테이블을 제안드려봅니다! ㅎㅎ 컬럼은 `id`(PK), `user_id`, `chat_room_id`, `nickname`, `status(탈퇴 여부)` `created_at` 정도로 생각해보았습니다 ㅎ 


제가 놓친 부분도 있을 듯 하여,, 마음에 드시는(?) 제안만 반영부탁드립니다 🙇 
혹시 불명확한 부분이나 논의가 필요한 부분은 내일 회의 때 정해보아도 좋을 것 같습니다 ㅎㅎ 감사합니다!

**Comment by mrlee7** [comment]
> 오 drawSQL 깔끔하네요! 빠르게 틀 잡아주셔서 감사합니다 🙇
> 
> 몇 가지 떠오른 아이디어 공유 드려봅니다 ㅎ
> 
> 1. `keyword`와 `archived_keyword` 테이블을 하나로 합치면 어떨까 하는 생각이 들었습니다! 키워드가 top 10 rank에서 밀려나거나 재진입할 때마다 동일한 레코드가 두 테이블에서 업데이트되는 일이 빈번해질 것 같아 `keyword` 테이블에 `archived` 컬럼을 두는 것은 어떨지 제안드려봅니다 ㅎㅎ (컬럼 중복을 최소화할 수 있다는 장점이 있을 것 같습니다!)
> 2. 생각해보니 `keyword`와 `chat_room` 도 거의 1:1의 동일한 개념이니 하나로 합쳐도 괜찮지 않을까 하는 생각이 드는군용,, 🤔 (둘을 분리해야할 이유가 크게 없다면 테이블 join 횟수를 줄이는 방향이 성능상 이점이 있지 않을까 생각했습니다)
> 3. (유찬님께서 회원가입 구현 방향을 제안해주셨던 기억이 있어서..) 모든 유저들의 정보를 저장하는 user 테이블을 제안드려봅니다 ㅎ 컬럼은 `id`(PK), `email`, `created_at` 정도로 생각했습니다.
> 4. 챗과 유저의 관계가 N:M이고, 노티를 보낼 때 해당 챗에 참여한 멤버 리스트가 필요할 것 같아서, 챗에 참가한 멤버리스트를 저장하는 `chat_member` 테이블을 제안드려봅니다! ㅎㅎ 컬럼은 `id`(PK), `user_id`, `chat_room_id`, `nickname`, `status(탈퇴 여부)` `created_at` 정도로 생각해보았습니다 ㅎ
> 
> 제가 놓친 부분도 있을 듯 하여,, 마음에 드시는(?) 제안만 반영부탁드립니다 🙇 혹시 불명확한 부분이나 논의가 필요한 부분은 내일 회의 때 정해보아도 좋을 것 같습니다 ㅎㅎ 감사합니다!

1, 좋습니다 ! 👍 `status` 라는 컬럼을 두고 enum 타입으로 해당 키워드의 상태를 관리하는 것은 어떠실까요 ? 
  `ACTIVE`, `ACTIVTE_PENDING`, `ARCHIVED`, `DELETE` 로 두고 각 enum 별로 로직을 부여하면 요구 명세에 따라 유연하게 구현이 가능하지 않을까 싶습니다. 🤔 

2. 아래 의견에 대해 채련님의 의견 부탁드립니다 ! 🙇   
- 검색어 순위에 따라 insert/update/delete 가 발생할 수 있다고 보았습니다. 
- 채팅방은 몇명 입장했는지, 최근 채팅이 발생한 일시와 같은 데이터가 추후 기록될 수 있다고 생각합니다 :)   

나눠서 생각해보자면 keyword는 배치에 의해 처리되는 케이스가 많을 것 같고(DML), chat_room은 클라이언트의 API 호출(SELETE/UPDATE)에 의해 처리되는 케이스가 많을 것 같은데요 !  이런 케이스에서 각 테이블에서 빈번히 발생되는 쿼리의 유즈케이스가 각기 다를 것이기에 분리되는 것도 좋을 것 같다는 의견입니다. 

abc라는 키워드에 의해 채팅방 A가 개설되었고, 검색어 순위에서 제외되어 A라는 채팅방이 소멸된 후 abc가 검색어 순위 재진입 시, B라는 채팅방이 개설된다는 관점에서 1:N의 테이블 설계를 유지하는 것이 어떨지 의견을 여쭤봅니다 🙇 

`채널 데이터 및 채팅 데이터 관리` 라는 이슈에서는 유저에 대한 스키마를 크게 고려하지 않았습니다.  
말씀주신 3,4 항목에 대해서는 유저 관련 설계 이슈에서 함께 논의해보면 어떨까요 ? 😄  

좋은 의견 주셔서 감사합니다 🙇 
많이 배웠습니다 ! 📖

**Comment by coderclcl** [comment]
> 1, 좋습니다 ! 👍 status 라는 컬럼을 두고 enum 타입으로 해당 키워드의 상태를 관리하는 것은 어떠실까요 ?
ACTIVE, ACTIVTE_PENDING, ARCHIVED, DELETE 로 두고 각 enum 별로 로직을 부여하면 요구 명세에 따라 유연하게 구현이 가능하지 않을까 싶습니다. 🤔

오 넵!! 제가 제안드린 것보다 더 좋은 방법인 것 같습니다! 👍  감사합니다 🙇 
혹시 각 enum은 아래와 같은 의미가 맞을까요?? 
- `ACTIVE`: 현재 top 10에 진입된 상태 
- `ACTIVTE_PENDING`: top 10에서 밀려났지만 (재진입 가능성 때문에) 대기중인 상태 
- `ARCHIVED`: top 10에서 밀려났고, 대기 시간도 지난 상태 (아카이브됨) 
- `DELETE`: (요건 유즈 케이스가 당장 떠오르지 않는군용,, 🤔 혹시 생각하신 유즈케이스가 있으실까요?.?) 


> 2. 아래 의견에 대해 채련님의 의견 부탁드립니다 ! 🙇
> - 검색어 순위에 따라 insert/update/delete 가 발생할 수 있다고 보았습니다.
> - 채팅방은 몇명 입장했는지, 최근 채팅이 발생한 일시와 같은 데이터가 추후 기록될 수 있다고 생각합니다 :)

> 나눠서 생각해보자면 keyword는 배치에 의해 처리되는 케이스가 많을 것 같고(DML), chat_room은 클라이언트의 API 호출(SELETE/UPDATE)에 의해 처리되는 케이스가 많을 것 같은데요 ! 이런 케이스에서 각 테이블에서 빈번히 발생되는 쿼리의 유즈케이스가 각기 다를 것이기에 분리되는 것도 좋을 것 같다는 의견입니다.
> abc라는 키워드에 의해 채팅방 A가 개설되었고, 검색어 순위에서 제외되어 A라는 채팅방이 소멸된 후 abc가 검색어 순위 재진입 시, B라는 채팅방이 개설된다는 관점에서 1:N의 테이블 설계를 유지하는 것이 어떨지 의견을 여쭤봅니다 🙇

아하 키워드:채팅방 = 1:N 으로 보고 계시군요!! 그렇다면 키워드와 채팅방 테이블 분리해두는 것 좋은 것 같습니다 👍 

> 채널 데이터 및 채팅 데이터 관리 라는 이슈에서는 유저에 대한 스키마를 크게 고려하지 않았습니다.
말씀주신 3,4 항목에 대해서는 유저 관련 설계 이슈에서 함께 논의해보면 어떨까요 ? 😄

넵!! 좋습니다 😄 

저도 많이 배웠습니다 🙇 🙇 감사합니다!!

**Comment by coderclcl** [comment]
혹시 PR https://github.com/booooomb/api/pull/10 리뷰도 바로 필요하시면 말씀해주세요~! 감사합니다 🙇

**Comment by mrlee7** [comment]
> 혹시 PR #10 리뷰도 바로 필요하시면 말씀해주세요~! 감사합니다 🙇

네네 리뷰 요청드립니다😆
감사합니다!
